apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dev
  name: pod-reader
rules:
- apiGroups: [""] #"" it indicate the core api
  resources: ["pod"]
  verbs: ["get","watch","list"]
