apiVersion: v1
kind: Pod
metadata:
  name: storagepod1
spec:
  containers:
    - name: pod1
      image: nginx
      resources:
        limits:
          memory: "800Mi"
          cpu: "800m"
        requests:
          memory: "600Mi"
          cpu: "400m"  
