apiVersion: v1
kind: Pod
metadata:
  name: storagepod2
spec:
  containers:
    - name: pod1
      image: redis
      resources:
        limits:
          memory: "1Gi"
          cpu: "800m"
        requests:
          memory: "700Mi"
          cpu: "400m"  
